name: flutter_boost
description: A next-generation Flutter-Native hybrid solution. FlutterBoost is a Flutter plugin which enables hybrid integration of Flutter for your existing native apps with minimum efforts.
version: 3.0.0

homepage: https://github.com/alibaba/flutter_boost

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  pigeon: ^3.2.7

flutter:
  plugin:
    platforms:
      android:
        package: com.idlefish.flutterboost
        pluginClass: FlutterBoostPlugin
      ios:
        pluginClass: FlutterBoostPlugin
